### ISSUE TITLE
Can tfdf work with a streaming tf dataset?

### ISSUE THREAD

**Issue by sibyjackgrove** [tensorflow/decision-forests#10]
My training data is in a multi GB CSV file. I have built a data pipeline using tf.data to stream this data and do some pre-processing,. Can I use these dataset objects in tfdf model.fit (similar to how it is done in Keras) or does tfdf need the dataset to have all the data stored in memory?

**Comment by achoum** [comment]
Currently, all the dataset needs to fit in memory.

You can (and it is a good idea in this case) to feed the dataset as a stream using a tf.dataset. See the [dataset section](https://github.com/tensorflow/decision-forests/blob/main/documentation/migration.md#dataset-io) of the migration guide for more details. However, the memory consumption will still be ~4bytes per values + index.

See my comments on [this issues](https://github.com/tensorflow/decision-forests/issues/12) for some details on how to optimize the ram consumption.
