### ISSUE TITLE
KeyError: 'SimpleMLLoadModelFromPathWithHandle' while loading model

### ISSUE THREAD

**Issue by jaya-shankar** [tensorflow/decision-forests#108]
Hey 👋,

I have been trying to load my saved Random Forest model for my flask application, 
I referred to the following article [https://www.tensorflow.org/tfx/tutorials/serving/rest_simple]( https://www.tensorflow.org/tfx/tutorials/serving/rest_simple)
and but when I load I get this error
` **FileNotFoundError: Op type not registered 'SimpleMLLoadModelFromPathWithHandle**' in binary running on b5d47309d41b. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
 You may be trying to load on a different device from the computational device. Consider setting the `experimental_io_device` option in `tf.saved_model.LoadOptions` to the io_device such as '/job:localhost'. `

I used the following code to save:
`model.save("/content/DSS_project/my_saved_model")`

To load in another colab after uploading the saved model used the following code
`loaded_model = keras.models.load_model('/content/DSS_project/my_saved_model')`
`loaded_model.compile(metrics=['accuracy'])`

I ran the following code mentioned in the above article:
`!saved_model_cli show --dir "/content/DSS_project/my_saved_model" --all`
and got the same error as the above

To replicate the error here is my colab code : [https://colab.research.google.com/drive/1CvUxWnmesTcTCSfki-8QLs5BjqVE1jRP?usp=sharing](https://colab.research.google.com/drive/1CvUxWnmesTcTCSfki-8QLs5BjqVE1jRP?usp=sharing)
By running all cells you can see the total error message

Thank you!

**Comment by rstz** [comment]
Hi, 
thank you for the report and for sharing the colab, we will have a look at it. From a very initial look at the colab, I think root_path needs to become `root_path = "/content/DSS_project/sample-ds" in order find file `final_combined_df.csv`, is that correct?

**Comment by jaya-shankar** [comment]
yeah! apologies, I forgot to change the rooth_path,
you are right!

**Comment by rstz** [comment]
What you're trying to do might require a bit of work. 

TF-DF uses custom Tensorflow ops (e.g. `SimpleMLLoadModelFromPathWithHandle`). Statically compiled binaries such as saved_model_cli or TF Serving need to be recompiled with TF-DF as a dependency in order to recognize these ops. We have instructions on how to do this here: https://www.tensorflow.org/decision_forests/tensorflow_serving

**Comment by rstz** [comment]
Closing this since there exist instructions to partly address this issue.
