### ISSUE TITLE
Is the random_seed parameter working correctly ?

### ISSUE THREAD

**Issue by tlapusan** [tensorflow/decision-forests#109]
Hi, 
I'm training a model using RandomForestModel and set the random_seed at initialization time. But for different trainings (for the same setup) I do have different accuracies and also different tree structures (for tree_index = 0)

If I set the random_seed, I would expect to have the same tree structures and metrics for different trainings. Is this an issue or is intended ?

Bellow I will put some screenshots with model setup and different tree structures for different trainings.

tfdf version = 0.2.4, python 3.8.2

<img width="780" alt="Screenshot 2022-05-20 at 09 58 25" src="https://user-images.githubusercontent.com/12815158/169471954-446b0897-6351-4703-8f78-3ab82cbaaf68.png">
<img width="729" alt="Screenshot 2022-05-20 at 09 58 31" src="https://user-images.githubusercontent.com/12815158/169471958-a29bca59-4fc7-403f-ba09-ff0ebe8fb17e.png">
<img width="980" alt="Screenshot 2022-05-20 at 10 01 08" src="https://user-images.githubusercontent.com/12815158/169471960-ead480b4-557c-4101-bd17-742167eabb8c.png">

**Comment by rstz** [comment]
Hi Tudor,
We haven't observed any bugs with the random_seed parameter and I wasn't able to reproduce this immediately. Just to confirm: Is it possible that the train_test_split function you're using is randomized and therefore influencing the results?

**Comment by tlapusan** [comment]
Hi @rstz,

thanks a lot. You are right, train_test_split was the issue.
