### ISSUE TITLE
Does TensorFlow Dececision Forests support batch training?

### ISSUE THREAD

**Issue by wangbingnan136** [tensorflow/decision-forests#110]

**Comment by rstz** [comment]
TF-DF always trains on the full dataset after it is read, hence the model quality will not vary based on the batch size. In other words, you can modify the batch size for IO speed (as is done for example in the [model composition tutorial](https://www.tensorflow.org/decision_forests/tutorials/model_composition_colab)), but there is not need to tune the batch size. See the section [Do not tune the batch size](https://github.com/tensorflow/decision-forests/blob/main/documentation/migration.md#do-not-tune-the-batch-size) in the migration guide.
