### ISSUE TITLE
Create custom tensorflow serving image with tfdf ops

### ISSUE THREAD

**Issue by martinbomio** [tensorflow/decision-forests#112]
Right now, TFDF models cannot be served through tensorflow serving because there are some tfdf ops that are not available in core tensorflow.

There are other tensorflow ecosystem libraries such as [struct2tensor](https://github.com/google/struct2tensor/blob/master/struct2tensor/tools/tf_serving_docker/Dockerfile) and [tf-scann](https://github.com/google-research/google-research/blob/master/scann/tf_serving/Dockerfile) that are already creating a custom tensorflow-serving image for their libraries. Would be great if tfdf also offers something like this.

**Comment by rstz** [comment]
Hi Martin,

Thank you for the feedback, streamlining our integration into TF-Serving is something we're very interested in.

We have released a [TF-Serving binary](https://github.com/tensorflow/decision-forests/releases/tag/serving-0.2.6) for the current version, let us know if that suits your needs. There also exist [instructions](https://github.com/tensorflow/decision-forests/blob/main/documentation/tensorflow_serving.md) for building such images yourself. Please let us know if these options suit your needs.
