### ISSUE TITLE
Multiple outputs with TFDF

### ISSUE THREAD

**Issue by goleng** [tensorflow/decision-forests#119]
Hi, 

I have a basic question about  multi-output regression and multi-label classification using TFDF package. 
Does TFDF support such cases? If yes, are there some examples on how to implement such models with TFDF and some caveat to be mindful of? 

Thanks.

**Comment by mrsergazinov** [comment]
Hey! It  appears this capability is not supported. See issue here: https://github.com/tensorflow/decision-forests/issues/19

**Comment by goleng** [comment]
@mrsergazinov Thanks for the pointer. Appreciate!
