### ISSUE TITLE
Cannot serve using precompiled tf-serving. Error: `GLIBC_2.33' not found

### ISSUE THREAD

**Issue by SpenceLunderman** [tensorflow/decision-forests#124]
Hi! 

I am trying to serve the test tf-df example `decision-forests/examples/minimal.py` (aptly named `tf-df-example` below) using the precompiled `tf-serving`. Unfortunately, I am running into numerous `GLIBC_X.XX not found` errors like this:
```
/usr/bin/tensorflow_model_server: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/bin/tensorflow_model_server)
```

Best guess is that the issue has to do with the difference between the system that precompiled `tensorflow_model_server_linux.zip` and what I am in pulling as the base: `tensorflow/serving:2.9.1`.  I have tried others, but ultimately this same `GLIBC_X.XX not found` error pops up and I'm not sure where to go from here (aside from trying to compile myself).

Any thoughts or suggestions would be greatly appreciated. Thanks!

Here is the set up.
1. `Dockerfile`:
```
FROM tensorflow/serving:2.9.1 as base

# Install curl
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl unzip \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN curl -LJO "https://github.com/tensorflow/decision-forests/releases/download/serving-0.2.6/tensorflow_model_server_linux.zip"
RUN unzip -o tensorflow_model_server_linux.zip -d /usr/bin/

COPY tf-df_serving_entrypoint.sh /usr/bin/tf-df_serving_entrypoint.sh
COPY /models/tf-df-example/ /tensorflow/models/tf-df-example/

WORKDIR /tensorflow/
ENTRYPOINT ["/usr/bin/tf-df_serving_entrypoint.sh"]
```

2. `tf-df_serving_entrypoint.sh`: 
```
# Using prebuild binary set in dockerfile
TFSERVING="/usr/bin/tensorflow_model_server"

# Configure the model path and name.
MODEL_PATH=/tensorflow/models/tf-df-example/
MODEL_NAME=tf-df-example

# Start a TF Serving server
${TFSERVING} \
    --rest_api_port=8501 \
    --model_name=${MODEL_NAME} \
    --model_base_path=${MODEL_PATH}
```

3. To build and run:
```
docker build . -t tfdf/serving
docker run -t --rm -p 8501:8501 tfdf/serving 
```

**Comment by rstz** [comment]
Hi Spence,

thank you for reporting this - I will try to reproduce and report back to you with results. If you're interested, you can also try compiling it yourself in the meantime https://github.com/tensorflow/decision-forests/blob/main/documentation/tensorflow_serving.md

**Comment by n-clinton** [comment]
Same issue.  Any info about the compile environment would be welcome.

**Comment by SpenceLunderman** [comment]
Update: 

I was able to compile tf-df into `tensorflow/serving:2.8.2-devel` which took a few hours. This allowed me to save the serving binary as shown [here](https://github.com/tensorflow/decision-forests/blob/main/tools/tf_serving/build_tf_serving_with_tf_df.sh#L65-L66) and then use the steps I outline above to compile tf-df into `tensorflow/serving:2.8.2` using the zipped serving binary I just made. 

There was no special reason for using 2.8.2, it just matched my needs. But an answer to the original question would still be great so other's don't have to compile themselves.

**Comment by achoum** [comment]
Hi,

**Analysis**

The pre-compiled version of tf-serving with TF-DF was compiled with GLIBC 2.33.
We we need to figure why.

```shell
> ldd tensorflow_model_server
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6
> /lib/x86_64-linux-gnu/libc.so.6
GNU C Library (Debian GLIBC 2.33-8) release release version 2.33.
```

The official pre-compiled version of tf-serving seems to use GLIBC 2.27.


```shell
# In a TF Serving Dev docker
> ldd `which ls` | grep libc
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6
> /lib/x86_64-linux-gnu/libc.so.6
GNU C Library (Ubuntu GLIBC 2.27-3ubuntu1.6) stable release version 2.27.
```

**Solutions**

- Compiling like @SpenceLunderman following [those instructions](https://www.tensorflow.org/decision_forests/tensorflow_serving) is a good first solution.
- We will release a new pre-compiled version using GLIBC 2.27.
- TF Decision Forests will be integrated in TF Serving soon. Likely in the next release (in ~2.5 months).

**Comment by SpenceLunderman** [comment]
> * TF Decision Forests will be integrated in TF Serving soon. Likely in the next release (in ~2.5 months).
Fantastic early Christmas present.

**Comment by achoum** [comment]
Would you mind testing the following pre-compiled version of TF Serving and make sure it does not raise any `GLIBC_X.XX not found` error?

https://github.com/tensorflow/decision-forests/releases/tag/serving-1.0.1

Simply running the following command should be enought:

```shell
./tensorflow_model_server --rest_api_port=8501 --model_name=my_model --model_base_path=/model_path
```

**Comment by wuflyh** [comment]
> Would you mind testing the following pre-compiled version of TF Serving and make sure it does not raise any `GLIBC_X.XX not found` error?
> 
> https://github.com/tensorflow/decision-forests/releases/tag/serving-1.0.1
> 
> Simply running the following command should be enought:
> 
> ```shell
> ./tensorflow_model_server --rest_api_port=8501 --model_name=my_model --model_base_path=/model_path
> ```

Thanks for quick fix. However, now it outputs the following issue when I run it on a docker with ubuntu 20.04. This is an attempt to load the example Random Forest model on the adult dataset.

2022-09-16 17:15:53.010066: I tensorflow_serving/model_servers/server.cc:89] Building single TensorFlow model file config:  model_name: my_model model_base_path: /tmp/my_saved_model_with_version
2022-09-16 17:15:53.010494: I tensorflow_serving/model_servers/server_core.cc:465] Adding/updating models.
2022-09-16 17:15:53.010582: I tensorflow_serving/model_servers/server_core.cc:594]  (Re-)adding model: my_model
2022-09-16 17:15:53.249538: I tensorflow_serving/core/basic_manager.cc:740] Successfully reserved resources to load servable {name: my_model version: 1}
2022-09-16 17:15:53.249636: I tensorflow_serving/core/loader_harness.cc:66] Approving load for servable version {name: my_model version: 1}
2022-09-16 17:15:53.249738: I tensorflow_serving/core/loader_harness.cc:74] Loading servable version {name: my_model version: 1}
2022-09-16 17:15:53.249892: I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:45] Reading SavedModel from: /tmp/my_saved_model_with_version/1
2022-09-16 17:15:53.253439: I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:89] Reading meta graph with tags { serve }
2022-09-16 17:15:53.253512: I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:130] Reading SavedModel debug info (if present) from: /tmp/my_saved_model_with_version/1
2022-09-16 17:15:53.253748: I external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-09-16 17:15:53.298888: I external/org_tensorflow/tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:348] MLIR V1 optimization pass is not enabled
2022-09-16 17:15:53.301220: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:229] Restoring SavedModel bundle.
**terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc**
 Aborted                 ${TFSERVING} --rest_api_port=8501 --model_name=${MODEL_NAME} --model_base_path=${MODEL_PATH}

**Comment by SpenceLunderman** [comment]
@achoum Thanks for the update! I will test soon and get back to you.

@wuflyh I hit this error a lot in my testing and I'm pretty sure it has to do with `tensorflow/serving:2.9.X`.  You can test this by serving a non-tfdf model using a `tensorflow/serving:2.9.X` docker image. I hit this error a lot which is why I ended up using the `tensorflow/serving:2.8.2` image when compiling tfdf serving.

**Comment by wuflyh** [comment]
@SpenceLunderman Thank you for your reply. I need to serve a tfdf model and I have no environment compiling the binary tensorflow serving on my own.

**Comment by achoum** [comment]
@wuflyh Thanks for the test an report. This is not the kind of things we want to append in the release :). I'll keep you in touch.

@SpenceLunderman Thanks a lot for the clue.

**Comment by achoum** [comment]
There was [a little bug](https://github.com/tensorflow/tensorflow/commit/1ecf591f4826cd980e5269a3deac40f937833248
) in TensorFlow. Would you mind once again testing the (updated) pre-compiled version of TF Serving? :)

https://github.com/tensorflow/decision-forests/releases/tag/serving-1.0.1

**Comment by wuflyh** [comment]
Thanks @achoum now it works!

**Comment by achoum** [comment]
Awesome :)

The change will included in the next [the nightly docker](https://hub.docker.com/r/tensorflow/serving/tags) build of TF Serving. Hopefully in the following days.
