### ISSUE TITLE
"The list of available hyper-parameters is available at: go/simple_ml/hyper_parameters "

### ISSUE THREAD

**Issue by TheJeran** [tensorflow/decision-forests#125]
I can't find a list of hyper parameters. On the core page under learner_params https://www.tensorflow.org/decision_forests/api_docs/python/tfdf/keras/CoreModel

It simply says 

`"Hyper-parameters for the learner. The list of available hyper-parameters is available at: go/simple_ml/hyper_parameters."`

Is this an error?

**Comment by TheJeran** [comment]
I just found this tutorial
https://colab.research.google.com/github/tensorflow/decision-forests/blob/main/documentation/tutorials/automatic_tuning_colab.ipynb#scrollTo=Dm_lJxjkyatR

Which links to this page

https://github.com/google/yggdrasil-decision-forests/blob/main/documentation/learners.md

which appear to be the hyperparameters. 

Seeing as a google search for "go/simple_ml/hyper_parameters" only yields two results both of which are the sentences above... I would suggest updating it?

**Comment by rstz** [comment]
You are right, the link is incorrect. Thank you for looking up the correct one. This will be updated with the next update to the Tensorflow website.
