### ISSUE TITLE
Tensorflow-datasets 'label' problem

### ISSUE THREAD

**Issue by KirillRnd** [tensorflow/decision-forests#126]
Hello, I met an unexpected behavior during usage of tensorflow datasets. An extremely simple example below:

```
import tensorflow_datasets as tfds 
import tensorflow_decision_forests as tfdf

train_set_batched = tfds.load('mnist', split='train').batch(128)
model = tfdf.keras.GradientBoostedTreesModel()
model.fit(train_set_batched)
```

Whereas the model expects to see a 'label' in the data, tfds has contained this key already:

```
ValueError: No label received for training. If you used `pd_dataframe_to_tf_dataset`, make sure to specify the `label` argument. data={'image': <tf.Tensor 'data:0' shape=(None, 28, 28, 1) dtype=uint8>, 'label': <tf.Tensor 'data_1:0' shape=(None,) dtype=int64>}
```
It seems that the 'label' is provided in the unexpected way. My libraries versions:

```
tensorflow-datasets==4.6.0
tensorflow-decision-forests==0.2.7
tensorflow==2.9.1
```

**Comment by rstz** [comment]
Hi,

the label needs to be the second channel of the Tensorflow dataset provided, the column name doesn't matter. 

For more information about using TF.datasets, you can check out the [intermediate colab](https://www.tensorflow.org/decision_forests/tutorials/intermediate_colab), which contains a full example with the glue/sst2 dataset.
