### ISSUE TITLE
Can't fit on dataset from tf.data.Dataset.load()

### ISSUE THREAD

**Issue by bermeitinger-b** [tensorflow/decision-forests#131]
I'm using heavy (pre-)preprocessing in generating the dataset, so I'd like to outsource this, and save the data conveniently as a `tf.data.Dataset` with `ds.save('ds')`
The dataset is valid and created with the `tfdf.keras.pd_dataframe_to_tf_dataset` function.

However, when loading the dataset with `tf.data.Dataset.load('ds')`, the model complains that it's not a "batched" dataset:
```
ValueError: The dataset does not contain a 'batch' operation. TF-DF models should be trained with batch operations. Add a batch operations to solve this issue. Alternatively, you can disabled this check with the constructor argument `check_dataset=False`. If this message is a false positive, please let us know so we can improve this dataset check logic.
```

Manually, batching and prefetching (`ds.batch(1000).prefetch(4)`) results with the error message

```
Cannot batch tensors with different shapes in component 0. First element had shape [1000] and element 38 had shape [376].
	 [[{{node IteratorGetNext}}]] [Op:__inference_adapt_step_115]
```

Here is a colab with the penguins example: https://colab.research.google.com/gist/bermeitinger-b/6d1ec28066f865da5366618b6c406535/cant-fit-on-loaded-tf-data-dataset.ipynb

**Comment by rstz** [comment]
Hi, 
thank you for the detailed report. 
At first sight, this looks like an issue with the dataset checking. Could you try if everything works well if you disable it, i.e. use `tfdf.keras.RandomForestModel(check_dataset=False)`?

**Comment by achoum** [comment]
TF-DF checks that the dataset contains a `batch` operation. However, in the case of an exported-reloaded dataset (`tf.data.Dataset.load` in your colab), this detection does not seems to work. See the error message:

> ValueError: The dataset does not contain a 'batch' operation. TF-DF models should be trained with batch operations. Add a batch operations to solve this issue. Alternatively, you can disabled this check with the constructor argument `check_dataset=False`. If this message is a false positive, please let us know so we can improve this dataset check logic.

I've create a bug report for us to resolve this issue. 
In the mean time, as @rstz mentioned, disabling the checking should solve the issue.
