### ISSUE TITLE
NotFoundError when load model from different device

### ISSUE THREAD

**Issue by ihsanramdhani** [tensorflow/decision-forests#14]
i got an error when load model using `keras.models.load_model` from different devices. This is my complete code:
`from tensorflow import keras`
`model_path = '/content/drive/MyDrive/saved_model/my_model'`
`imported = keras.models.load_model(model_path) `
 

I got an error like this:
`NotFoundError: Op type not registered 'SimpleMLCreateModelResource' in binary running on 135bfc4bd927. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
`

The training and evaluation was completed successfully

**Comment by achoum** [comment]
Thanks for the report.

**Solution**

Can you try importing TF-DF before loading the model?:

```python
import tensorflow_decision_forests as tfdf
from tensorflow import keras

model_path = '/content/drive/MyDrive/saved_model/my_model'
imported = keras.models.load_model(model_path)
```

**Explanation**

TF-DF relies on [a couple](https://github.com/tensorflow/decision-forests/blob/main/tensorflow_decision_forests/tensorflow/ops/inference/op.cc) of TensorFlow custom ops. These ops need to be loaded manually (which happen when importing TF-DF).

**Comment by ihsanramdhani** [comment]
Its working!! Thanks

**Comment by Koushik667** [comment]
Hello @achoum, i am getting the same errror when i save the model in python using model.save and then load the model using  tensorflow C API. Can you please let me know if we can use tensorflow decsion forest model in C API?
