### ISSUE TITLE
No Mac Release for 1.1.0 on PyPi

### ISSUE THREAD

**Issue by fsonntag** [tensorflow/decision-forests#144]
Hey,

I noticed that there's no Mac release for 1.1.0.

Is it possible to also release one? :) 

1.0.1 on PyPI
![Screen Shot 2565-11-25 at 16 25 43](https://user-images.githubusercontent.com/1186111/203946539-529c4d0b-7711-47dd-8d50-197bae3928e2.png)

1.1.0 on PyPI
![Screen Shot 2565-11-25 at 16 25 56](https://user-images.githubusercontent.com/1186111/203946548-62897f37-0d77-43cd-95ef-2ed12163b593.png)

**Comment by rstz** [comment]
Hi Felix,

yes, we will release a version for Mac soon. I'm currently waiting for Tensorflow to release an M1-compatible version 2.11, see [PyPi](https://pypi.org/project/tensorflow-macos/), which usually takes ~2 weeks. As soon as this is out, TF-DF will follow.

**Comment by fsonntag** [comment]
Thanks a lot for the feedback :)

**Comment by rstz** [comment]
Update We have 1.1.0 packages for Apple CPUs now (M1, M2, ...) on Pypi now. Intel CPUs to come as well.

**Comment by rstz** [comment]
Packages for Intel CPUs are available now.

Happy holidays everyone!

**Comment by fsonntag** [comment]
Thanks a lot :)
