### ISSUE TITLE
Contributing Tutorial 

### ISSUE THREAD

**Issue by shivance** [tensorflow/decision-forests#147]
Hi,
I'm a Kaggler, and I find tf-decision-forests very useful. Thus I want to contribute tutorials to the library ! 
Are tutorials contributions being accepted ? If yes then tutorials on which topics are currently in wishlist?

**Comment by rstz** [comment]
Hi,

we are always happy to accept contributions for TF-DF tutorials. You can add them to https://github.com/tensorflow/decision-forests/blob/main/documentation/more_examples.md

We don't have an active wishlist, but anything not yet covered by our existing tutorials would be great. Let us know if you need assistence
