### ISSUE TITLE
Intermediate colab is erroring out.  See attached. 

### ISSUE THREAD

**Issue by stevewalker-de** [tensorflow/decision-forests#15]
![5D7A75AC-80F3-4301-BC26-A465BB05CE43](https://user-images.githubusercontent.com/67876607/120109364-c0aaaf80-c12e-11eb-9a23-693021532ad7.png)
![0432A780-4473-49FC-8933-46B1D5065361](https://user-images.githubusercontent.com/67876607/120109366-c0aaaf80-c12e-11eb-91d4-e1b47a272c66.png)

**Comment by achoum** [comment]
Thanks for the report.

There seems to be a transient problem with the SST2 dataset in TensorFlow Dataset.

The owners have been alerted. I'll update this issue once resolved.

**Comment by achoum** [comment]
The nightly version of TensorFlow Datasets does not have this issues.
The colab has been updated with this temporary fix.

Existing codes can be updated by running the following commands before importing `tensorflow_datasets`:

```python
!pip install tfds-nightly -U --quiet

import tensorflow_datasets as tfds
all_ds = tfds.load("glue/sst2")
```
