### ISSUE TITLE
TF 2.9.0 and TFDF 0.2.5 no distribution found messages

### ISSUE THREAD

**Issue by dubrovin-sudo** [tensorflow/decision-forests#161]
Dear Gentlemen,
I tried to install TFDF according to [Compatibility table](https://github.com/tensorflow/decision-forests/blob/main/documentation/known_issues.md#compatibility-table) and I an got error:

(metal-venv) jayokocha@Aleksandrs-MacBook-Pro Light_weight_network % pip install tensorflow-decision-forests==0.2.5
ERROR: Could not find a version that satisfies the requirement tensorflow-decision-forests==0.2.5 (from versions: 0.2.3, 0.2.4, 1.0.1, 1.1.0, 1.2.0)
ERROR: No matching distribution found for tensorflow-decision-forests==0.2.5

**Comment by rstz** [comment]
Hi,
Tensorflow Decision Forests 0.2.5 was not released for MacOS, so please use an earlier version of TF-DF, if possible.

Additional note: We've recently gotten reports that TF-DF is incompatible with tensorflow-metal. If you experience this issue, please let us know.

**Comment by dubrovin-sudo** [comment]
Hi! Yes, I'm using tensorflow-metal. Earlier version of TF-DF incompatible with TF 2.9.0

**Comment by rstz** [comment]
Closing this since we have a parallel discussing in https://github.com/tensorflow/decision-forests/issues/152#issuecomment-1436571168
