### ISSUE TITLE
Error asking to report bug to tensorflow

### ISSUE THREAD

**Issue by Sreyashi-Bhattacharjee** [tensorflow/decision-forests#162]
Hi, I am trying to run a use-case following the sample given on this page - [https://www.tensorflow.org/decision_forests](tensorflow_url) .
I am getting the following error:

<img width="518" alt="error_1" src="https://user-images.githubusercontent.com/40518134/217166087-238a7372-dfef-4978-8849-8753f8be04f6.png">

<img width="493" alt="error_2" src="https://user-images.githubusercontent.com/40518134/217166097-09ed2dfd-ec4b-462c-bece-6312852ba43f.png">

Execution details:
Tabular data using model = tfdf.keras.GradientBoostedTreesModel() and following exact steps in the above link.

Please help.

**Comment by rstz** [comment]
Hi,

can you please provide a colab with a minimal example to reproduce the error?

**Comment by rstz** [comment]
Closing this, feel free to reopen if the problem persists
