### ISSUE TITLE
Faild in multi-class classification 

### ISSUE THREAD

**Issue by mohammad69h94** [tensorflow/decision-forests#174]
In the tensorflow website, You mentioned that "RandomForestModel" support multi-class classification.  In composing ANN with RFM we have problem,  it's not possible to do this.
Nobody could not have use it as multi-class until now. And then please correct your opinion.

**Comment by rstz** [comment]
Hi,

Tensorflow Decision Forests supports multi-class classification. Our [Beginner tutorial](https://www.tensorflow.org/decision_forests/tutorials/beginner_colab#training_a_random_forest_model) shows how to use TF-DF with Random Forests for multi-class classification on the penguins dataset.

**Comment by janpfeifer** [comment]
Btw, just in case, notice that multi-class != [multi-label (wikipedia)](https://en.m.wikipedia.org/wiki/Multi-label_classification).

**Comment by mohammad69h94** [comment]
> Hi,
> 
> Tensorflow Decision Forests supports multi-class classification. Our [Beginner tutorial](https://www.tensorflow.org/decision_forests/tutorials/beginner_colab#training_a_random_forest_model) shows how to use TF-DF with Random Forests for multi-class classification on the penguins dataset.

If you consider my comment, I wrote in composing ANN and decision forest. This not possible to do this.

**Comment by mohammad69h94** [comment]
> Btw, just in case, notice that multi-class != [multi-label (wikipedia)](https://en.m.wikipedia.org/wiki/Multi-label_classification).

If you consider my comment, I wrote in composing ANN and decision forest. This not possible to do this.
