### ISSUE TITLE
label not found in tfdf.keras.pd_dataframe_to_tf_dataset

### ISSUE THREAD

**Issue by 284nnuS** [tensorflow/decision-forests#179]
Hello,

I have a excel file with this column name : 
![image](https://github.com/tensorflow/decision-forests/assets/91007431/0c787783-5f67-4fc4-a509-57e7fcc28a62)
But when i run the command : 
`tfdf.keras.pd_dataframe_to_tf_dataset(train_df, label="Applied Solutions")`
I received the error KeyError: "['Applied Solutions'] not found in axis". 
How can i solve that? 
Please help me.

Thanks

**Comment by rstz** [comment]
This is not a useful repro, please provide Python code. Closing this issue for now.
