### ISSUE TITLE
model_plotter.plot_model_in_colab has No response

### ISSUE THREAD

**Issue by 983183947** [tensorflow/decision-forests#183]
I use model_plotter.plot_model_in_colab has no response（not show image）

**Comment by rstz** [comment]
Hi, can you please share a reproduction notebook on https://colab.research.google.com/ ?

**Comment by 983183947** [comment]
code in colab is ok。but when i use tensorflow with  docker it not show image。

**Comment by rstz** [comment]
Hi, this method only works in Colab, so this is WIP.

You can get the HTML representation of the model with `plot_model(model)` and view that with any html viewer you want, or you can get a text representation of the individual trees via `inspector.extract_tree(tree_idx=IDX_OF_THE_TREE_YOU_CARE_ABOUT).pretty()`
