### ISSUE TITLE
no wheels for apple silicon (macos-arm64)

### ISSUE THREAD

**Issue by rbasa349** [tensorflow/decision-forests#200]
Hello! After version 1.6.0 there are no wheels for macos-arm64, could you fix this please?

 **--- 1.8.0 ---** 

![image](https://github.com/tensorflow/decision-forests/assets/116624984/e64b7f42-4ffe-44e3-b741-ba666f9dea0d)

 **--- 1.7.0 ---** 

![image](https://github.com/tensorflow/decision-forests/assets/116624984/ee3af069-507b-4fbf-ada1-55500d3e345a)

 **--- 1.6.0 ---** 

![image](https://github.com/tensorflow/decision-forests/assets/116624984/be5e138c-1618-40ef-8462-d2f7dd57786f)

**Comment by rstz** [comment]
Hi, thank you for notifying us, we will upload the weeks shortly

**Comment by rstz** [comment]
Arm64 wheels for 1.8.0 are now available on Pypi
