### ISSUE TITLE
Using a re-loaded model for prediction or evaluation is giving error

### ISSUE THREAD

**Issue by sibyjackgrove** [tensorflow/decision-forests#21]
I am able to save and then re-load a model. But when I use the re-loaded model for prediction or evaluation, I get the following error:

```
model.save("hypermodels/model")
model = tf.keras.models.load_model("hypermodels/model/")
energy_predictions = model.predict(train_ds,verbose=1)
```

```
InvalidArgumentError:  Unexpected dimension of numerical_features bank.
	 [[{{node gradient_boosted_trees_model_1/StatefulPartitionedCall/StatefulPartitionedCall/inference_op}}]] [Op:__inference_predict_function_28619]

Function call stack:
predict_function
```

**Comment by sibyjackgrove** [comment]
@achoum 

> 
> Also, can you make sure "hypermodels/model/" does not contains a model before calling "save". Overriding a model in Keras is only allowed if the new model is an increment (e.g. more training) of the existing model as the model's assets are not overridden.

It seems this was the problem. I was saving to a folder that had a previous model. I deleted the folder and saved it again. Now the re-loaded model is working for fit, evaluate, and predict.

**Comment by achoum** [comment]
Awesome. Thanks for the feedback.

We'll add a check and an error message for this situation in the next release.
