### ISSUE TITLE
Decision forest documentation link is broken in the Main page

### ISSUE THREAD

**Issue by sonali8434** [tensorflow/decision-forests#216]
Please fix the decision forest documentation link. If maintainers allow me to do so, I can open a PR to correct this particular issue.

I have attached the screen recording for you. 

https://github.com/tensorflow/decision-forests/assets/109299402/be059aa7-59c0-4f11-9670-1155786ca0da

Thank You for your time.
Sonali Kumari

**Comment by achoum** [comment]
Thanks a lot for the alert. It will be fixed in the next doc release.
The target link should be: https://developers.google.com/machine-learning/decision-forests

**Comment by sonali8434** [comment]
Thank you for your quick response.
