### ISSUE TITLE
predict_log_proba support

### ISSUE THREAD

**Issue by Howard-ll** [tensorflow/decision-forests#26]
Hi

Could you support something like model.predict_log_proba?
The last layer of TFDF should have something like sigmoid(A) or exp(A) to make [0, 1] ranged output. This is good.
However, I also do need A output without sigmoid or exp. This will allow me to have much wider ranged output than sigmoid(A) or exp(A).
Hope that you consider this positively because this is very important to my tasks ;-)
Really look forward to seeing this feature on next release

Thanks a lot!

**Comment by achoum** [comment]
Hi Howard,

Thanks for the feature request :).

The feature has been implemented and will be available in the next TF-DF release (0.1.7; ETA: end of week or early next week).

**Comment by Howard-ll** [comment]
Hi, when I tried to call predict_log_proba on 0.1.7, I got an error as follows

score = self.clf.predict_log_proba(x_selected)
AttributeError: 'RandomForestModel' object has no attribute 'predict_log_proba'
