### ISSUE TITLE
Please support threads or processes

### ISSUE THREAD

**Issue by Howard-ll** [tensorflow/decision-forests#39]
**background**
If GPU support is difficult (and takes long), multiple threads or processes can speed up inference as well

**feature request**
Could you support a parameter like n_jobs? 

![image](https://user-images.githubusercontent.com/85953851/126025313-c274ef0f-a1b5-4bfc-b4d4-8f1416be7f94.png)

**Comment by achoum** [comment]
Hi,

Thanks for the ping and feature request.

> Regarding multi-threading

The training code of the RF and GBT is already multi-threaded. The number of threads is 6 by default.

This number of threads can be configured with the [num_threads](https://github.com/google/yggdrasil-decision-forests/blob/main/yggdrasil_decision_forests/learner/abstract_learner.proto#L45) field in the deployment spec of the [advanced argument](https://www.tensorflow.org/decision_forests/api_docs/python/tfdf/keras/AdvancedArguments).

However, this is feels like an obscure parameter, so I'll make sure to surface it.

**Feature request:** Move the `num_threads` argument to the model's object constructor.

> Multi-process

Multi-process training (e.g. training on 100s of machines) will be released in mid Q3 (probably ~ end September).

Cheers,

**Comment by achoum** [comment]
Training multi-threading is now available with the `num_threads` model constructor argument, e.g.:

```python
model = tfdf.keras.GradientBoostedTreesModel(num_threads=40)
```

Inference is still done in a single thread.

Note that the inference code is thread safe. Therefore, you can call it from multiple threads at the same time.
