### ISSUE TITLE
mkdtemp not getting cleaned up

### ISSUE THREAD

**Issue by jacksonloper** [tensorflow/decision-forests#41]
I just ran out of space on /tmp/ after training about 200 decision forests.  I think the temporary directory created at https://github.com/tensorflow/decision-forests/blob/58a5eb0187e8b4c391eca1ba02c2406b5adabfc5/tensorflow_decision_forests/keras/core.py#L378 is never cleaned up, even after the python process ends.  Each model that I was training required about 20 megs.  So after 200 models I had 4 gigs in /tmp/ and my operating system said "what is all that doing there??" and got mad at me.  

I have two ideas about this.
1. It seems like it should be possible to insist that the learner doesn't use disk unless explicitly permitted by the user.   But perhaps that is wildly naive.
1. It looks like the temporary directory is only actually used in `_train_model`.  So we should be able to use a  https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory context manager, just for that call (unless the user explicitly provdes a temporary directory).

Thoughts?

**Comment by achoum** [comment]
Hi jacksonloper,

Thanks for the alert and suggestions :).

**Background**

The training method takes a [temp_directory](https://github.com/tensorflow/decision-forests/blob/main/tensorflow_decision_forests/keras/core.py#L347) argument. If not provided, the argument defaults to [tempfile.mkdtemp()](https://docs.python.org/3/library/tempfile.html#tempfile.mkdtemp). As you noticed, unlike something like TemporaryDirectory, mkdtemp does not remove the files.

This directory is in fact not used for training ([ydf](https://github.com/google/yggdrasil-decision-forests) does not require a temp directory for training). Instead, the directory is used to store the TF SavedModel assets after training. In other words, if the temps directory is removed after training, the model will work fine (e.g. you can can `predict`), but it won't be possible to export it (e.g. model.save).

The temp_directory also serves another purpose. The model kept in RAM is [a compiled](https://github.com/google/yggdrasil-decision-forests/blob/main/documentation/user_manual.md#fast-engine) version optimized for the specific hardware. The compiled version is generally significantly smaller than the original model. However, the compilation is a non-reversible operation. Therefore, the temp_directory is the only full copy of the model.

**Your proposed solutions**

>> 1. It seems like it should be possible to insist that the learner doesn't use disk unless explicitly permitted by the user. But perhaps that is wildly naive.

This might be possible. See new proposed solutions 4 and 5.

>> 2. It looks like the temporary directory is only actually used in _train_model. So we should be able to use a https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory context manager, just for that call (unless the user explicitly provides a temporary directory).

There need to be a logic to keep the model temp directory (if the user wants to).


**New proposed solutions**

3. [easy] Document the logic described above to the user ([pydoc](https://github.com/tensorflow/decision-forests/blob/main/tensorflow_decision_forests/keras/core.py#L254) and [mddoc](https://github.com/tensorflow/decision-forests/tree/main/documentation)). Create an example (e.g. doc or colab) where the temp_directory is created and removed by the user. Pro: Existing solution.

4. [easy] Add an argument to remove the use of the temp_directory and make the model **non-serializable** (great if you don't expect to export the model after training). Pro: The most efficient solution (memory and disk IO) if the user does not care about the model. Con: separate path for the creation of the TF Model object.

5. [some work] Add an argument to remove the use of the temp_directory while keeping the model **serializable**. The non-compiled model will be kept in memory (alongside the compiled model). Pro: No need for a tmp directory. Con: higher memory usage.

wdyt?

**Comment by janpfeifer** [comment]
Some thoughts:

3. It gets my vote for a good default, but like happened with @jacksonloper, one may run out of disk-space during, let's say when doing hyperparameter tuning -- a common use case ...

3.b. Would it be possible/safe to improve solution 3 by adding a `.__del__()` method, or a `weakref.finalize()` to remove the files, if the model gets garbage collected ? As described in:

https://docs.python.org/3.6/library/weakref.html#comparing-finalizers-with-del-methods

This way the disk-space and memory-space will be kind of bound together. 

4.  Handy option, +1 to having this (as a non-default option).

5. +1 to having this option as well, but non-default because of the larger memory footprint. But with 3b they will become somewhat similar (since both are garbage collected).

**Comment by achoum** [comment]
The solution 3.b was implemented in TF-DF 0.1.8.
By default, the temp directory is linked to the model object.
