### ISSUE TITLE
Unable to import tensorflow_decision_forests

### ISSUE THREAD

**Issue by hokmingkwan** [tensorflow/decision-forests#51]
After `!pip install tensorflow_decision_forests --upgrade` and try to `import tensorflow_decision_forests as tfdf`, 
I found this error `NotFoundError: /opt/conda/lib/python3.7/site-packages/tensorflow_decision_forests/tensorflow/ops/training/training.so: undefined symbol: _ZN10tensorflow11GetNodeAttrERKNS_9AttrSliceEN4absl14lts_2020_09_2311string_viewEPSs`

I've tried to uninstall the tensorflow and reinstall the tensorflow==2.3.0, but does not work. 
Please let me know if you have any comments

**Comment by yufeidu** [comment]
I am also having this issue. I am running Python 3.9.6 on Arch Linux. I installed Tensorflow Decision Forests and all the dependencies with pip (i.e. I didn't use any of the packages from the Arch repository).

**Comment by arvnds** [comment]
Hi hokmingkwan and yufeidu,

It seems that tensorflow_decision_forests was broken by the tensorflow 2.6 release. We are working on releasing a new pip package that will work with tf 2.6, but in the meantime, it will work if you install tensorflow 2.5.1 explicitly, i.e. `pip install tensorflow==2.5.1` rather than `pip install tensorflow`.

I will keep this issue open until we release the new package. Thanks for the report!

**Comment by janpfeifer** [comment]
Yes, we apologize for the delay ... we'll get better on catching up future TF releases.

We just released a "pre-release" of the library compatible with TF2.6, see #54 . Needs to be installed manually -- or wait next week and we will upload to PyPI.

**Comment by hiydavid** [comment]
> Hi hokmingkwan and yufeidu,
> 
> It seems that tensorflow_decision_forests was broken by the tensorflow 2.6 release. We are working on releasing a new pip package that will work with tf 2.6, but in the meantime, it will work if you install tensorflow 2.5.1 explicitly, i.e. `pip install tensorflow==2.5.1` rather than `pip install tensorflow`.
> 
> I will keep this issue open until we release the new package. Thanks for the report!

Tried this and it worked! thanks

**Comment by achoum** [comment]
TF-DF v0.1.9 (released today) is compatible with TF2.6 :)
