### ISSUE TITLE
Tensorflow decision forests after  update to tf 2.6.0

### ISSUE THREAD

**Issue by lukebor** [tensorflow/decision-forests#54]
There is a problem with Tensorflow_decision_forests after updating to version 2.6.0

here is the gist https://colab.research.google.com/gist/lukebor/70f7abd84d547bf39c4a8b47394e7017/beginner_colab.ipynb

I have used tensorflow beginner tutorial and upgraded the tf. If there is other way to import tfdf please let me know

**Comment by janpfeifer** [comment]
Thanks for reporting @lukebor . We are aware of the issue and working on the ABI issues to prepare the new release of TF-DF for TF 2.6.

**Comment by janpfeifer** [comment]
Just an update: we have a wheel working for TF 2.6. Fixing some minor things, and we will likely upload it to MyPI early next week.

**Comment by arvnds** [comment]
We have released a version of TF-DF compatible with TF 2.6, see https://github.com/tensorflow/decision-forests/releases/tag/0.1.9rc1 -- unfortunately we are still testing this release and will upload it to PyPi soon. In the meantime, if you urgently need the fix, please install the wheels manually.

We will close this issue when the latest version on PyPi is TF 2.6 compatible.

**Comment by achoum** [comment]
The v0.1.9 was released. It is compatible with TF2.6.
