### ISSUE TITLE
Performance issues in tensorflow_decision_forests/keras/keras_test.py(P2)

### ISSUE THREAD

**Issue by DLPerf** [tensorflow/decision-forests#55]
Hello,I found a performance issue in the definition of `_synthetic_train_and_test` ,
tensorflow_decision_forests/keras/keras_test.py,
[ compression_type="GZIP").map(parse)](https://github.com/tensorflow/decision-forests/blob/3b0da039839fa9ce5710e39cc609d493ce543002/tensorflow_decision_forests/keras/keras_test.py#L951) was called without **num_parallel_calls**.
I think it will increase the efficiency of your program if you add this.

The same issues also exist in [ test_path, compression_type="GZIP").map(parse).batch(50).map(preprocess)
](https://github.com/tensorflow/decision-forests/blob/3b0da039839fa9ce5710e39cc609d493ce543002/tensorflow_decision_forests/keras/keras_test.py#L953) 

Here is [the documemtation of tensorflow](https://tensorflow.google.cn/api_docs/python/tf/data/Dataset?hl=en#map) to support this thing.

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by SaultanBeagama** [comment]
ليه

**Comment by achoum** [comment]
Hi,

Could you please elaborate on why this is performance issue, and what are the expected gains? Keep in mind that tests are running in parallel.

It seems you proposed the exact same change to many tensorflow github projects. I suspect you developed some tools to assist you. Independently of this particular issue, it would be interesting to learn more about it :)
