### ISSUE TITLE
Features importance

### ISSUE THREAD

**Issue by tsachiblauamat** [tensorflow/decision-forests#56]
Hey,

I ran the feature significant and compared the results to Sklearn output. not only the results are different, but also the results that I'm getting using this implementation doesn't make any sense(using the info that I have about my data).
for example a feature that is constant is one of the most significant features(it got the heights value).

maybe I don't know how to read the output properly?
("data:0.33" (1; #27), 235)
this means that feature number 27 got score of 235?

Tsachi

**Comment by SaultanBeagama** [comment]
في الأحد، ٢٢ أغسطس، ٢٠٢١ ٣:١٠ م tsachiblauamat ***@***.***>
كتب:

**Comment by janpfeifer** [comment]
I'm sorry @SaultanBeagama, we need better documentation for these.

Can you display the output of `model.summary()` after training ? It will pretty-print the variable importances, it may become obvious ?

**Comment by achoum** [comment]
Hi tsachiblauamat,

Thanks for the ping.
The different variable importances (VIs) are described [here](https://github.com/google/yggdrasil-decision-forests/blob/main/documentation/user_manual.md#variable-importances). This documentation should propagate soon to the [TF-DF documentation](https://www.tensorflow.org/decision_forests/api_docs/python/tfdf/inspector/AbstractInspector#variable_importances).

In your example `("data:0.33" (1; #27), 235)`, 235 is effectively the score of the VI. However, we need the VI name to make sense of it :).

Constant features are not used by the model. Therefore, the VI of such feature should be the "worst" possible one (the "worst" value depends on the semantic of the VI). Unless specified, the greater the score, the most important the feature. Currently, the one exception is the `MEAN_MIN_DEPTH` VI (see doc).

As Jan mentioned, printing the `model.summary()` would help understand the situation. 

Cheers,
M.

**Comment by mainguyenanhvu** [comment]
I read in (your example)[https://www.tensorflow.org/decision_forests/tutorials/advanced_colab]
```
# Mean decrease in AUC of the class 1 vs the others.
inspector.variable_importances()["MEAN_DECREASE_IN_AUC_1_VS_OTHERS"]
```
with output:
```
[("bill_length_mm" (1; #1), 0.06972998903508787),
 ("flipper_length_mm" (1; #3), 0.008532072368420462),
 ("island" (4; #4), 0.004488760964911687),
 ("bill_depth_mm" (1; #0), 0.0032552083333338144),
 ("year" (1; #6), 0.0022101151315789824),
 ("sex" (4; #5), 0.0004625822368422572),
 ("body_mass_g" (1; #2), -5.1398026315596645e-05)]
```

I wonder that what do number in tuple mean?
