### ISSUE TITLE
XGBoost Implementation

### ISSUE THREAD

**Issue by Timo3as** [tensorflow/decision-forests#64]
Hi all, 

I'm trying to implement XGBoost, using GradientBoostedTreesModel with use_hessian_gain. After some tweaking of the parameter, while working with different datasets on binary classification problem, I cannot replicate the trees and results of xgboost's XGBClassifier; but as far as I understand, it should produce the same algorithm.

Did somebody tried this, or is this even possible? If yes can you point me in the direction of how I need to configure GradientBoostedTreesModel and if not is there an implementation of XGBoost planned?

Thanks so much in advance,

Timo

**Comment by achoum** [comment]
Hi Timo3as,

I replies to your question in the [Yggdrasil issue](https://github.com/google/yggdrasil-decision-forests/issues/13).

Cheers :),
M.
