### ISSUE TITLE
TFDF 0.2.2 breaks printing of training logs

### ISSUE THREAD

**Issue by semenko** [tensorflow/decision-forests#73]
In the latest version of TFDF (0.2.2), displaying training logs seems to have broken. 

e.g. this no longer prints detailed training logs.
```
with sys_pipes():
  model_1.fit(x=train_ds)
```

This used to print detailed training logs and debug info. Now it prints (as of 0.2.2):
```
Training GradientBoostedTrees classification model on: XXXXXXX
Resolve hyper-parameter template "benchmark_rank1" to "benchmark_rank1@v1" -> {'growing_strategy':  …
Use /tmp/tmpqp29oi53 as temporary training directory
Starting reading the dataset
1/1 [==============================] - ETA: 0s
Dataset read in 0:00:00.552562
Training model
Model trained in 0:00:00.058688
Compiling model
1/1 [==============================] - 1s 626ms/step
```

**Comment by semenko** [comment]
Ah, I see this in the changelog at https://github.com/tensorflow/decision-forests/blob/main/CHANGELOG.md

You can get the old behavior by passing  verbose=2 to .fit(), e.g. model_1.fit(x=train_ds, verbose=2)

(Closing this, though the examples need to be updated.)

**Comment by achoum** [comment]
Hi @semenko,

The 0.2.2 release changed the training log system to make it more similar to other Keras models. The amount of printed training logs is controlled by the `verbose` constructor or `fit` arguments as follow:

verbose=0 => No training logs.
verbose=1 (default) => a little bit of training logs.
verbose=2 => All the training logs.

Notably, "with sys_pipes():" is not required anymore.

In your case, replace

```python
model = tfdf.keras.GradientBoostedTreesModel()
with sys_pipes():
    model.fit(train_ds)
```

by

```python
model = tfdf.keras.GradientBoostedTreesModel(verbose=2)
model.fit(train_ds)
```
