### ISSUE TITLE
UsageError: Line magic function `%set_cell_height` not found.

### ISSUE THREAD

**Issue by wuhongsheng** [tensorflow/decision-forests#74]
I tried to find the following error in Google colab

UsageError: Line magic function `%set_cell_height` not found.

**Comment by achoum** [comment]
The `set_cell_height` colab-magic method is defined at the top of the colabs in a collapsed cell.

For example, search for "The hidden code cell limits the output height in colab." in the [beginner colab](https://www.tensorflow.org/decision_forests/tutorials/beginner_colab) and you will find:

```python
# Some of the model training logs can cover the full
# screen if not compressed to a smaller viewport.
# This magic allows setting a max height for a cell.
@register_line_magic
def set_cell_height(size):
  display(
      Javascript("google.colab.output.setIframeHeight(0, true, {maxHeight: " +
                 str(size) + "})"))
```

**Comment by wuhongsheng** [comment]
Thank you so much
