### ISSUE TITLE
python version 3.8 in test_bazel.sh 

### ISSUE THREAD

**Issue by huulocmedvnu** [tensorflow/decision-forests#82]
python version 3.8 in bazel.sh make other python version can't install this library.

**Comment by achoum** [comment]
That a good point. I'll change the line to `python3`.

Note however, this won't prevent you to use the library with any other python versions. Once the library is build (this is the same process for all python version), the library package is build by `build_pip_package.sh`. This script takes a python version as an argument (e.g. `build_pip_package.sh python3.9`) or run over all the available version (e.g. `build_pip_package.sh ALL_VERSIONS`; see the file header for more details).

**Comment by huulocmedvnu** [comment]
Thank you. That is very helpful
