### ISSUE TITLE
model.predict() error on TFDF model after saving

### ISSUE THREAD

**Issue by mmiller8878** [tensorflow/decision-forests#86]
I have a keras model that includes 2 TFDFs. Essentially, the first random forest makes a prediction and the second random forest attempts to predict the error of the first model. See model plot below:

![image](https://user-images.githubusercontent.com/24652999/157640708-8a6e4740-51bd-43b1-89b9-bd26c7241f71.png)

This model predicts fine, until I save and reload from disk. Then the `Model.predict()` method fails. I've narrowed it down to an error in the second random forest but not sure where to go from there as the loaded model appears identical to the non-loaded one. 

Here's an as-minimal-as-I-could-make it illustration of the problem in google colab: https://colab.research.google.com/drive/1YIqI-M7y1hPwKCRTHBqqiybhxGkCxfza?usp=sharing

**Comment by achoum** [comment]
Hi Matt,

Thanks for the colab. You spotted a bug :).
I'll update this issue once fixed.

In the meantime, there is unfortunately no elegant solution for you before the fix: The only current solution is to export both models separately, and re-combine them after loading them. 

In this setup, the two models are colliding during the SavedModel serialization. When the model is re-loaded, the first model is loaded twice (hence the internal error about shape mismatch; the two models have different input shapes).

Regarding the colab, you can simplify it a bit a follow:

```python
# Create the dataset
# Note: Make sure the dataset is "batched".
features = tf.random.uniform(shape=[100,2], minval=1, maxval=100)
target = tf.random.uniform(shape=[100,1], minval=25, maxval=50)
dataset = tf.data.Dataset.from_tensor_slices((features, target)).batch(32)

# Create graph
input = tf.keras.Input(shape=(2,))

m1 = tfdf.keras.RandomForestModel(num_trees=10,task=tfdf.keras.Task.REGRESSION)

m2 = tfdf.keras.RandomForestModel(num_trees=10,task=tfdf.keras.Task.REGRESSION)

def m2_preprocessing(x):
  return tf.concat([m1(x),x],axis=1)
m2_pred = m2(m2_preprocessing(input))

super_model = tf.keras.models.Model(input, m2_pred)
tf.keras.utils.plot_model(super_model, show_shapes=True)

# Train first model
m1.fit(dataset)

# Train second model
def mix(x,y):
  return m2_preprocessing(x), y
m2.fit(dataset.map(mix))

# save then reload the models
super_model.save("super_model", overwrite=True)

super_model.predict([[1,1]])
```

The example can be further simplified, using the "preprocessing" model argument:

```python

# Create datset
features = tf.random.uniform(shape=[100,2], minval=1, maxval=100)
target = tf.random.uniform(shape=[100,1], minval=25, maxval=50)
dataset = tf.data.Dataset.from_tensor_slices((features, target)).batch(32)

# Create graph
m1 = tfdf.keras.RandomForestModel(num_trees=10,task=tfdf.keras.Task.REGRESSION)

def m2_preprocessing(x):
  return tf.concat([m1(x),x],axis=1)

m2 = tfdf.keras.RandomForestModel(num_trees=10,task=tfdf.keras.Task.REGRESSION, preprocessing=m2_preprocessing)

input = tf.keras.Input(shape=(2,))
super_model = tf.keras.models.Model(input, m2(input))
super_model._tracking_m1 = m1

# Train both models
m1.fit(dataset)
m2.fit(dataset)

# save then reload the models
super_model.predict([[1,1]])
super_model.save("/tmp/super_model2", overwrite=True)
```

**Comment by mmiller8878** [comment]
Thanks for the quick reply! The workaround of saving the separate models then recombining works.  Appreciate the code simplification as well.

**Comment by rstz** [comment]
Thanks again for spotting this bug. The fix for the underlying issue has landed at HEAD and will be included in the next version.
