### ISSUE TITLE
How to get probabilities for all classes?

### ISSUE THREAD

**Issue by siddharthchauhan** [tensorflow/decision-forests#9]
I want to predict the probabilities of all classes in multiclass classification problem. How do i do it?

**Comment by achoum** [comment]
Calling `predict` on a multi-class classification model returns an array of probabilities and of shape [num_examples, num_classes].

```python
train_ds = # classification dataset with >2 classes.
model.fit(train_ds)
predictions = model.predict(test_ds)

# Predicted probability for the second classe of the the first example.
predictions[0,1]
```
The [Palmer's Penguins tutorial section](https://www.tensorflow.org/decision_forests/tutorials/beginner_colab#training_a_random_forest_model) for an example of multi-class model.
